name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Set image tag
      id: vars
      run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -t emmaeasy/diabetes-model-api:${{ env.TAG }} .

    - name: Push Docker image to Docker Hub
      run: docker push emmaeasy/diabetes-model-api:${{ env.TAG }}

    - name: Update kube_deploy.yml with new image tag
      run: |
        sed -i "s|image: emmaeasy/diabetes-model-api:.*|image: emmaeasy/diabetes-model-api:${{ env.TAG }}|" kube_deploy.yml

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add kube_deploy.yml
        git commit -m "Update image tag to ${{ env.TAG }}"
        git push



# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main  # Trigger pipdelinde on push to main branch

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2

#     - name: Log in to Docker Hub
#       run: echo "${{ secrets.Docker_Tocken }}" | docker login -u "emmaeasy" --password-stdin

#     - name: Build Docker image
#       run: docker build -t docker build -t diabetes-model-api .

#     - name: Push Docker image to Docker Hub
#       run: docker push emmaeasy/diabetes-model-api

